server:
  port: 8089

spring:
  datasource:
   name: test
   url: jdbc:mysql://localhost:3306/pslnvoicing?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=true
   username: root
   password: 123456
   type: com.alibaba.druid.pool.DruidDataSource
   driver-class-name: com.mysql.cj.jdbc.Driver

   jpa:
     show-sql: true
     database-platform: org.hibernate.dialect.MySQL5Dialect
     #database-platform: org.hibernate.dialect.Oracle10Dialect
     databse: mysql

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.pojos

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


#jpa:
#  database: mysql
#    database-platform: org.hibernate.dialect.MySQL5Dialect
#    show-sql: true
#  hibernate:
#    ddl-auto: update